//go:build linux

package main

// bpf2go compiles the kernel-side eBPF C program and generates Go wrappers
// such as bpfObjects, loadBpfObjects, and bpfNdEvent used below.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -no-strip -target amd64 -type nd_event bpf ../../bpf/networkdoctor.bpf.c -- -I../../bpf -I../..

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"math"
	"net"
	"net/http"
	"os"
	"os/signal"
	"runtime"
	"syscall"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/vishvananda/netlink"
	"golang.org/x/sys/unix"
)

const (
	ndHistBuckets = 32

	// Linux TCP state numbers used as keys in nd_tcp_state_delta.
	tcpEstablished = 1
	tcpTimeWait    = 6
)

// options contains runtime knobs exposed as CLI flags. Most threshold values
// are written into the BPF nd_config map so the kernel program can apply them.
type options struct {
	iface         string
	listen        string
	metricsPath   string
	gcInterval    time.Duration
	dnsTimeout    time.Duration
	udpIdle       time.Duration
	slowTCPRTT    time.Duration
	shortTCPConn  time.Duration
	slowDNS       time.Duration
	longUDPFlow   time.Duration
	highRunqlat   time.Duration
	retransWindow time.Duration
	eventCooldown time.Duration
	retransBurst  uint64
	cwndDropPct   uint64
}

func main() {
	var opts options
	flag.StringVar(&opts.iface, "iface", "eth0", "interface to attach TC ingress/egress programs to")
	flag.StringVar(&opts.listen, "listen", ":9102", "HTTP listen address for Prometheus metrics")
	flag.StringVar(&opts.metricsPath, "metrics-path", "/metrics", "Prometheus metrics path")
	flag.DurationVar(&opts.gcInterval, "gc-interval", 10*time.Second, "BPF map garbage collection interval")
	flag.DurationVar(&opts.dnsTimeout, "dns-timeout", 5*time.Second, "delete DNS pending entries older than this")
	flag.DurationVar(&opts.udpIdle, "udp-idle-timeout", 60*time.Second, "delete UDP flow entries idle for longer than this")
	flag.DurationVar(&opts.slowTCPRTT, "slow-tcp-rtt", 100*time.Millisecond, "slow TCP RTT threshold written to nd_config")
	flag.DurationVar(&opts.shortTCPConn, "short-tcp-conn", 100*time.Millisecond, "short TCP connection threshold written to nd_config")
	flag.DurationVar(&opts.slowDNS, "slow-dns", 50*time.Millisecond, "slow DNS threshold written to nd_config")
	flag.DurationVar(&opts.longUDPFlow, "long-udp-flow", 30*time.Second, "long UDP flow threshold written to nd_config")
	flag.DurationVar(&opts.highRunqlat, "high-runqlat", 5*time.Millisecond, "high run queue latency threshold written to nd_config")
	flag.DurationVar(&opts.retransWindow, "retrans-window", time.Second, "TCP retransmit burst window written to nd_config")
	flag.DurationVar(&opts.eventCooldown, "event-cooldown", 5*time.Second, "anomaly event cooldown written to nd_config")
	flag.Uint64Var(&opts.retransBurst, "retrans-burst", 3, "TCP retransmit burst count threshold written to nd_config")
	flag.Uint64Var(&opts.cwndDropPct, "cwnd-drop-percent", 50, "TCP cwnd drop percentage threshold written to nd_config")
	flag.Parse()

	if err := run(opts); err != nil {
		log.Fatalf("networkdoctor agent failed: %v", err)
	}
}

// run wires the agent together: load BPF programs/maps, attach hooks, start
// background readers, and expose BPF map contents as Prometheus metrics.
func run(opts options) error {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	// eBPF maps and programs may pin locked memory; this raises the memlock
	// limit for the current process where supported.
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock limit: %w", err)
	}

	// bpfObjects and loadBpfObjects are generated by bpf2go from
	// bpf/networkdoctor.bpf.c.
	var objs bpfObjects
	if err := loadBpfObjects(&objs, nil); err != nil {
		return fmt.Errorf("load BPF objects: %w", err)
	}
	defer objs.Close()

	if err := writeConfig(&objs, opts); err != nil {
		return fmt.Errorf("write nd_config: %w", err)
	}

	// Keep every attached link/filter as an io.Closer so shutdown can detach
	// hooks in reverse order.
	links, err := attachPrograms(&objs, opts.iface)
	if err != nil {
		return err
	}
	defer closeAll(links)

	rd, err := ringbuf.NewReader(objs.NdEvents)
	if err != nil {
		return fmt.Errorf("open nd_events ring buffer: %w", err)
	}
	defer rd.Close()

	go readEvents(ctx, rd)
	go runMapGC(ctx, &objs, opts.gcInterval, opts.dnsTimeout, opts.udpIdle)

	// Use a private registry so this endpoint only exposes NetworkDoctor
	// metrics, not process/runtime metrics from the default registry.
	reg := prometheus.NewRegistry()
	reg.MustRegister(newNetworkDoctorCollector(&objs))
	mux := http.NewServeMux()
	mux.Handle(opts.metricsPath, promhttp.HandlerFor(reg, promhttp.HandlerOpts{}))

	srv := &http.Server{
		Addr:              opts.listen,
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
	}

	errCh := make(chan error, 1)
	go func() {
		log.Printf("serving Prometheus metrics on %s%s", opts.listen, opts.metricsPath)
		errCh <- srv.ListenAndServe()
	}()

	select {
	case <-ctx.Done():
		// Closing the ring buffer reader unblocks readEvents before the HTTP
		// server drains outstanding requests.
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = rd.Close()
		return srv.Shutdown(shutdownCtx)
	case err := <-errCh:
		if errors.Is(err, http.ErrServerClosed) {
			return nil
		}
		return err
	}
}

// writeConfig copies CLI threshold values into the single-entry nd_config BPF
// array map. Durations are converted to the units used by the C program.
func writeConfig(objs *bpfObjects, opts options) error {
	key := uint32(0)
	cfg := bpfNdConfig{
		SlowTcpRttUs:         uint64(opts.slowTCPRTT / time.Microsecond),
		ShortTcpConnUs:       uint64(opts.shortTCPConn / time.Microsecond),
		SlowDnsUs:            uint64(opts.slowDNS / time.Microsecond),
		LongUdpFlowUs:        uint64(opts.longUDPFlow / time.Microsecond),
		HighRunqlatUs:        uint64(opts.highRunqlat / time.Microsecond),
		RetransBurstWindowNs: uint64(opts.retransWindow / time.Nanosecond),
		EventCooldownNs:      uint64(opts.eventCooldown / time.Nanosecond),
		RetransBurstCount:    opts.retransBurst,
		CwndDropPercent:      opts.cwndDropPct,
	}
	return objs.NdConfig.Update(&key, &cfg, ebpf.UpdateAny)
}

// attachPrograms attaches each generated BPF program to its kernel hook. The
// hook types mirror the SEC(...) declarations in networkdoctor.bpf.c.
func attachPrograms(objs *bpfObjects, iface string) ([]io.Closer, error) {
	var closers []io.Closer
	add := func(c io.Closer, err error) error {
		if err != nil {
			closeAll(closers)
			return err
		}
		closers = append(closers, c)
		return nil
	}

	// These hooks are raw tracepoints because the C program reads arguments
	// from struct bpf_raw_tracepoint_args.
	rawTracepoints := []struct {
		name string
		prog *ebpf.Program
	}{
		{"inet_sock_set_state", objs.NdInetSockSetState},
		{"tcp_retransmit_skb", objs.NdTcpRetransmitSkb},
		{"sched_wakeup", objs.NdSchedWakeup},
		{"sched_wakeup_new", objs.NdSchedWakeupNew},
		{"sched_switch", objs.NdSchedSwitch},
	}
	for _, rt := range rawTracepoints {
		l, err := link.AttachRawTracepoint(link.RawTracepointOptions{
			Name:    rt.name,
			Program: rt.prog,
		})
		if err != nil {
			closeAll(closers)
			return nil, fmt.Errorf("attach raw tracepoint %s: %w", rt.name, err)
		}
		closers = append(closers, l)
	}

	// tcp_rcv_established is currently attached with kprobe for broad kernel
	// compatibility. fentry can be faster, but requires a tracing program and
	// BTF support, so it should be added as a separate fallback-aware path.
	if err := add(link.Kprobe("tcp_rcv_established", objs.NdTcpRcvEstablished, nil)); err != nil {
		return nil, fmt.Errorf("attach kprobe tcp_rcv_established: %w", err)
	}

	// TC programs observe ingress/egress packets on the selected interface for
	// UDP flow and DNS latency accounting.
	tcClosers, err := attachTC(iface, objs.NdTcIngress, objs.NdTcEgress)
	if err != nil {
		closeAll(closers)
		return nil, fmt.Errorf("attach TC programs to %s: %w", iface, err)
	}
	closers = append(closers, tcClosers...)
	return closers, nil
}

// attachTC installs a clsact qdisc and replaces ingress/egress BPF filters on
// the requested network interface.
func attachTC(iface string, ingressProg, egressProg *ebpf.Program) ([]io.Closer, error) {
	dev, err := netlink.LinkByName(iface)
	if err != nil {
		return nil, fmt.Errorf("find interface: %w", err)
	}

	qdisc := &netlink.Clsact{
		QdiscAttrs: netlink.QdiscAttrs{
			LinkIndex: dev.Attrs().Index,
			Handle:    netlink.MakeHandle(0xffff, 0),
			Parent:    netlink.HANDLE_CLSACT,
		},
	}
	if err := netlink.QdiscAdd(qdisc); err != nil && !isExists(err) {
		return nil, fmt.Errorf("add clsact qdisc: %w", err)
	}

	// FilterReplace makes re-running the agent idempotent for the same filter
	// priority/name instead of failing on an existing filter.
	ingress := tcFilter(dev.Attrs().Index, netlink.HANDLE_MIN_INGRESS, 1, "nd_tc_ingress", ingressProg)
	egress := tcFilter(dev.Attrs().Index, netlink.HANDLE_MIN_EGRESS, 1, "nd_tc_egress", egressProg)

	for _, filter := range []*netlink.BpfFilter{ingress, egress} {
		if err := netlink.FilterReplace(filter); err != nil {
			return nil, fmt.Errorf("replace filter %s: %w", filter.Name, err)
		}
	}

	return []io.Closer{
		tcFilterCloser{filter: ingress},
		tcFilterCloser{filter: egress},
	}, nil
}

// tcFilter builds a direct-action BPF filter. Direct action means the BPF
// program returns TC_ACT_* values directly instead of using a separate action.
func tcFilter(linkIndex int, parent uint32, priority uint16, name string, prog *ebpf.Program) *netlink.BpfFilter {
	return &netlink.BpfFilter{
		FilterAttrs: netlink.FilterAttrs{
			LinkIndex: linkIndex,
			Parent:    parent,
			Handle:    netlink.MakeHandle(0, priority),
			Protocol:  unix.ETH_P_ALL,
			Priority:  priority,
		},
		Fd:           prog.FD(),
		Name:         name,
		DirectAction: true,
	}
}

// tcFilterCloser adapts netlink.FilterDel to io.Closer so TC filters can share
// the same cleanup path as cilium/ebpf links.
type tcFilterCloser struct {
	filter netlink.Filter
}

func (c tcFilterCloser) Close() error {
	err := netlink.FilterDel(c.filter)
	if err != nil && !isNotFound(err) {
		return err
	}
	return nil
}

// closeAll detaches resources in reverse attachment order, which is safer when
// later resources depend on earlier setup such as the clsact qdisc.
func closeAll(closers []io.Closer) {
	for i := len(closers) - 1; i >= 0; i-- {
		if err := closers[i].Close(); err != nil {
			log.Printf("close link: %v", err)
		}
	}
}

func isExists(err error) bool {
	return errors.Is(err, os.ErrExist) || errors.Is(err, syscall.EEXIST)
}

func isNotFound(err error) bool {
	return errors.Is(err, os.ErrNotExist) || errors.Is(err, syscall.ENOENT)
}

// readEvents consumes anomaly records emitted by the BPF ring buffer and logs
// them for now. A later backend can replace this with structured ingestion.
func readEvents(ctx context.Context, rd *ringbuf.Reader) {
	for {
		record, err := rd.Read()
		if err != nil {
			if ctx.Err() != nil || errors.Is(err, ringbuf.ErrClosed) {
				return
			}
			log.Printf("read ringbuf event: %v", err)
			continue
		}

		// bpfNdEvent is generated from struct nd_event in the C program. The
		// raw sample layout must stay in sync with that struct definition.
		var evt bpfNdEvent
		if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &evt); err != nil {
			log.Printf("decode ringbuf event: %v", err)
			continue
		}

		log.Printf(
			"anomaly event type=%d pid=%d ifindex=%d src=%s:%d dst=%s:%d value_us=%d aux=%d",
			evt.Type,
			evt.Pid,
			evt.Ifindex,
			ipv4String(evt.SrcIp),
			evt.SrcPort,
			ipv4String(evt.DstIp),
			evt.DstPort,
			evt.ValueUs,
			evt.Aux,
		)
	}
}

// runMapGC periodically removes stale entries from maps where the kernel side
// cannot safely know that a flow/query has timed out.
func runMapGC(ctx context.Context, objs *bpfObjects, interval, dnsTimeout, udpIdle time.Duration) {
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			now, err := monotonicNowNS()
			if err != nil {
				log.Printf("map gc: read monotonic time: %v", err)
				continue
			}

			dnsDeleted := gcDNSPending(objs.NdDnsPending, now, uint64(dnsTimeout/time.Nanosecond))
			udpDeleted := gcUDPFlows(objs.NdUdpFlows, now, uint64(udpIdle/time.Nanosecond))
			if dnsDeleted > 0 || udpDeleted > 0 {
				log.Printf("map gc deleted dns_pending=%d udp_flows=%d", dnsDeleted, udpDeleted)
			}
		}
	}
}

// monotonicNowNS returns CLOCK_MONOTONIC in nanoseconds so userspace timeout
// checks use the same time base as bpf_ktime_get_ns().
func monotonicNowNS() (uint64, error) {
	var ts unix.Timespec
	if err := unix.ClockGettime(unix.CLOCK_MONOTONIC, &ts); err != nil {
		return 0, err
	}
	return uint64(ts.Sec)*uint64(time.Second) + uint64(ts.Nsec), nil
}

// gcDNSPending deletes DNS query entries that never received a matching
// response before the configured timeout.
func gcDNSPending(m *ebpf.Map, nowNS, timeoutNS uint64) int {
	var key bpfNdDnsKey
	var val bpfNdDnsPendingValue
	deleted := 0

	iter := m.Iterate()
	for iter.Next(&key, &val) {
		if val.StartNs == 0 || nowNS <= val.StartNs || nowNS-val.StartNs <= timeoutNS {
			continue
		}
		if err := m.Delete(&key); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
			log.Printf("map gc: delete nd_dns_pending: %v", err)
			continue
		}
		deleted++
	}
	if err := iter.Err(); err != nil {
		log.Printf("map gc: iterate nd_dns_pending: %v", err)
	}
	return deleted
}

// gcUDPFlows deletes UDP flow state after it has been idle long enough. This
// keeps the LRU map from retaining old flows until pressure evicts them.
func gcUDPFlows(m *ebpf.Map, nowNS, idleNS uint64) int {
	var key bpfNdFlow4Key
	var val bpfNdUdpFlowValue
	deleted := 0

	iter := m.Iterate()
	for iter.Next(&key, &val) {
		if val.LastSeenNs == 0 || nowNS <= val.LastSeenNs || nowNS-val.LastSeenNs <= idleNS {
			continue
		}
		if err := m.Delete(&key); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
			log.Printf("map gc: delete nd_udp_flows: %v", err)
			continue
		}
		deleted++
	}
	if err := iter.Err(); err != nil {
		log.Printf("map gc: iterate nd_udp_flows: %v", err)
	}
	return deleted
}

// networkDoctorCollector is a custom Prometheus collector backed directly by
// BPF maps. Each scrape reads the latest map values and emits metrics.
type networkDoctorCollector struct {
	objs *bpfObjects

	tcpActive          *prometheus.Desc
	tcpTimeWait        *prometheus.Desc
	tcpClosed          *prometheus.Desc
	tcpConnectFailed   *prometheus.Desc
	tcpShortLived      *prometheus.Desc
	tcpConnectAttempts *prometheus.Desc
	tcpRetrans         *prometheus.Desc
	tcpRetransBurst    *prometheus.Desc
	tcpRTTSamples      *prometheus.Desc
	tcpCwndSamples     *prometheus.Desc

	dnsQueries     *prometheus.Desc
	dnsResponses   *prometheus.Desc
	dnsRcodeErrors *prometheus.Desc
	dnsSlow        *prometheus.Desc
	dnsRcode       *prometheus.Desc

	udpPackets   *prometheus.Desc
	udpLongFlows *prometheus.Desc

	tcpSRTTHist     *prometheus.Desc
	tcpCwndHist     *prometheus.Desc
	dnsLatencyHist  *prometheus.Desc
	runqlatHist     *prometheus.Desc
	udpDurationHist *prometheus.Desc
}

// newNetworkDoctorCollector defines metric descriptors once. The Collect
// method later supplies concrete values for each scrape.
func newNetworkDoctorCollector(objs *bpfObjects) *networkDoctorCollector {
	return &networkDoctorCollector{
		objs: objs,

		tcpActive:          prometheus.NewDesc("ebpf_tcp_connections_active", "Current TCP ESTABLISHED connection delta summed across CPUs.", nil, nil),
		tcpTimeWait:        prometheus.NewDesc("ebpf_tcp_connections_time_wait", "Current TCP TIME_WAIT connection delta summed across CPUs.", nil, nil),
		tcpClosed:          prometheus.NewDesc("ebpf_tcp_connections_closed_total", "TCP connections observed leaving ESTABLISHED.", nil, nil),
		tcpConnectFailed:   prometheus.NewDesc("ebpf_tcp_connect_failed_total", "TCP connect attempts that failed before ESTABLISHED.", nil, nil),
		tcpShortLived:      prometheus.NewDesc("ebpf_tcp_connections_short_lived_total", "TCP connections shorter than the configured threshold.", nil, nil),
		tcpConnectAttempts: prometheus.NewDesc("ebpf_tcp_connect_attempts_total", "TCP SYN-like state transitions observed.", nil, nil),
		tcpRetrans:         prometheus.NewDesc("ebpf_tcp_retransmits_total", "TCP retransmission events observed.", nil, nil),
		tcpRetransBurst:    prometheus.NewDesc("ebpf_tcp_retransmit_bursts_total", "TCP retransmission bursts exceeding the configured threshold.", nil, nil),
		tcpRTTSamples:      prometheus.NewDesc("ebpf_tcp_rtt_samples_total", "TCP RTT samples observed by tcp_rcv_established.", nil, nil),
		tcpCwndSamples:     prometheus.NewDesc("ebpf_tcp_cwnd_samples_total", "TCP cwnd samples observed by tcp_rcv_established.", nil, nil),

		dnsQueries:     prometheus.NewDesc("ebpf_dns_queries_total", "DNS queries observed on UDP port 53.", nil, nil),
		dnsResponses:   prometheus.NewDesc("ebpf_dns_responses_total", "DNS responses observed on UDP port 53.", nil, nil),
		dnsRcodeErrors: prometheus.NewDesc("ebpf_dns_rcode_errors_total", "DNS responses with non-zero rcode.", nil, nil),
		dnsSlow:        prometheus.NewDesc("ebpf_dns_slow_total", "DNS responses slower than the configured threshold.", nil, nil),
		dnsRcode:       prometheus.NewDesc("ebpf_dns_rcode_total", "DNS response count by rcode.", []string{"rcode"}, nil),

		udpPackets:   prometheus.NewDesc("ebpf_udp_packets_total", "UDP packets observed by TC programs.", nil, nil),
		udpLongFlows: prometheus.NewDesc("ebpf_udp_long_flows_total", "UDP flows exceeding the configured duration threshold.", nil, nil),

		tcpSRTTHist:     prometheus.NewDesc("ebpf_tcp_srtt_microseconds", "TCP SRTT samples exposed from log2 BPF buckets.", nil, nil),
		tcpCwndHist:     prometheus.NewDesc("ebpf_tcp_cwnd", "TCP congestion window samples exposed from log2 BPF buckets.", nil, nil),
		dnsLatencyHist:  prometheus.NewDesc("ebpf_dns_query_latency", "DNS query latency samples exposed from log2 BPF buckets.", nil, nil),
		runqlatHist:     prometheus.NewDesc("ebpf_runqlat", "Scheduler run queue latency samples exposed from log2 BPF buckets.", nil, nil),
		udpDurationHist: prometheus.NewDesc("ebpf_udp_session_duration", "Long UDP session duration samples exposed from log2 BPF buckets.", nil, nil),
	}
}

// Describe sends every metric descriptor to Prometheus during collector
// registration.
func (c *networkDoctorCollector) Describe(ch chan<- *prometheus.Desc) {
	ch <- c.tcpActive
	ch <- c.tcpTimeWait
	ch <- c.tcpClosed
	ch <- c.tcpConnectFailed
	ch <- c.tcpShortLived
	ch <- c.tcpConnectAttempts
	ch <- c.tcpRetrans
	ch <- c.tcpRetransBurst
	ch <- c.tcpRTTSamples
	ch <- c.tcpCwndSamples
	ch <- c.dnsQueries
	ch <- c.dnsResponses
	ch <- c.dnsRcodeErrors
	ch <- c.dnsSlow
	ch <- c.dnsRcode
	ch <- c.udpPackets
	ch <- c.udpLongFlows
	ch <- c.tcpSRTTHist
	ch <- c.tcpCwndHist
	ch <- c.dnsLatencyHist
	ch <- c.runqlatHist
	ch <- c.udpDurationHist
}

// Collect is called on every /metrics scrape. It converts BPF map counters and
// histograms into Prometheus metric samples.
func (c *networkDoctorCollector) Collect(ch chan<- prometheus.Metric) {
	ch <- prometheus.MustNewConstMetric(c.tcpActive, prometheus.GaugeValue, float64(sumTCPState(c.objs.NdTcpStateDelta, tcpEstablished)))
	ch <- prometheus.MustNewConstMetric(c.tcpTimeWait, prometheus.GaugeValue, float64(sumTCPState(c.objs.NdTcpStateDelta, tcpTimeWait)))

	tcp := sumTCPCounters(c.objs.NdTcpCounters)
	ch <- prometheus.MustNewConstMetric(c.tcpClosed, prometheus.CounterValue, float64(tcp.ClosedTotal))
	ch <- prometheus.MustNewConstMetric(c.tcpConnectFailed, prometheus.CounterValue, float64(tcp.ConnectFailedTotal))
	ch <- prometheus.MustNewConstMetric(c.tcpShortLived, prometheus.CounterValue, float64(tcp.ShortLivedTotal))
	ch <- prometheus.MustNewConstMetric(c.tcpConnectAttempts, prometheus.CounterValue, float64(tcp.ConnectAttemptTotal))
	ch <- prometheus.MustNewConstMetric(c.tcpRetrans, prometheus.CounterValue, float64(tcp.RetransTotal))
	ch <- prometheus.MustNewConstMetric(c.tcpRetransBurst, prometheus.CounterValue, float64(tcp.RetransBurstTotal))
	ch <- prometheus.MustNewConstMetric(c.tcpRTTSamples, prometheus.CounterValue, float64(tcp.RttSampleTotal))
	ch <- prometheus.MustNewConstMetric(c.tcpCwndSamples, prometheus.CounterValue, float64(tcp.CwndSampleTotal))

	dns := sumDNSCounters(c.objs.NdDnsCounters)
	ch <- prometheus.MustNewConstMetric(c.dnsQueries, prometheus.CounterValue, float64(dns.QueryTotal))
	ch <- prometheus.MustNewConstMetric(c.dnsResponses, prometheus.CounterValue, float64(dns.ResponseTotal))
	ch <- prometheus.MustNewConstMetric(c.dnsRcodeErrors, prometheus.CounterValue, float64(dns.RcodeErrorTotal))
	ch <- prometheus.MustNewConstMetric(c.dnsSlow, prometheus.CounterValue, float64(dns.SlowTotal))

	udp := sumUDPCounters(c.objs.NdUdpCounters)
	ch <- prometheus.MustNewConstMetric(c.udpPackets, prometheus.CounterValue, float64(udp.PacketTotal))
	ch <- prometheus.MustNewConstMetric(c.udpLongFlows, prometheus.CounterValue, float64(udp.LongFlowTotal))

	// Per-rcode counters and log2 histograms are stored as indexed BPF arrays,
	// so they need small helper loops instead of a single struct lookup.
	collectRcodeCounters(ch, c.dnsRcode, c.objs.NdDnsRcodeTotal)
	collectLog2Histogram(ch, c.tcpSRTTHist, c.objs.NdTcpSrttUsHist)
	collectLog2Histogram(ch, c.tcpCwndHist, c.objs.NdTcpCwndHist)
	collectLog2Histogram(ch, c.dnsLatencyHist, c.objs.NdDnsLatencyUsHist)
	collectLog2Histogram(ch, c.runqlatHist, c.objs.NdRunqlatUsHist)
	collectLog2Histogram(ch, c.udpDurationHist, c.objs.NdUdpDurationUsHist)
}

// sumTCPState reads the per-CPU state delta for a single TCP state and returns
// the sum across CPUs.
func sumTCPState(m *ebpf.Map, state uint32) int64 {
	values, err := lookupPerCPU[int64](m, state)
	if err != nil {
		log.Printf("collect nd_tcp_state_delta[%d]: %v", state, err)
		return 0
	}

	var total int64
	for _, v := range values {
		total += v
	}
	return total
}

// sumTCPCounters aggregates the per-CPU TCP counter struct into one total.
func sumTCPCounters(m *ebpf.Map) bpfNdTcpCounters {
	values, err := lookupPerCPU[bpfNdTcpCounters](m, 0)
	if err != nil {
		log.Printf("collect nd_tcp_counters: %v", err)
		return bpfNdTcpCounters{}
	}

	var total bpfNdTcpCounters
	for _, v := range values {
		total.ClosedTotal += v.ClosedTotal
		total.ShortLivedTotal += v.ShortLivedTotal
		total.ConnectAttemptTotal += v.ConnectAttemptTotal
		total.ConnectFailedTotal += v.ConnectFailedTotal
		total.RetransTotal += v.RetransTotal
		total.RetransBurstTotal += v.RetransBurstTotal
		total.RttSampleTotal += v.RttSampleTotal
		total.CwndSampleTotal += v.CwndSampleTotal
	}
	return total
}

// sumDNSCounters aggregates the per-CPU DNS counter struct into one total.
func sumDNSCounters(m *ebpf.Map) bpfNdDnsCounters {
	values, err := lookupPerCPU[bpfNdDnsCounters](m, 0)
	if err != nil {
		log.Printf("collect nd_dns_counters: %v", err)
		return bpfNdDnsCounters{}
	}

	var total bpfNdDnsCounters
	for _, v := range values {
		total.QueryTotal += v.QueryTotal
		total.ResponseTotal += v.ResponseTotal
		total.RcodeErrorTotal += v.RcodeErrorTotal
		total.SlowTotal += v.SlowTotal
	}
	return total
}

// sumUDPCounters aggregates the per-CPU UDP counter struct into one total.
func sumUDPCounters(m *ebpf.Map) bpfNdUdpCounters {
	values, err := lookupPerCPU[bpfNdUdpCounters](m, 0)
	if err != nil {
		log.Printf("collect nd_udp_counters: %v", err)
		return bpfNdUdpCounters{}
	}

	var total bpfNdUdpCounters
	for _, v := range values {
		total.PacketTotal += v.PacketTotal
		total.LongFlowTotal += v.LongFlowTotal
	}
	return total
}

// collectRcodeCounters exports one Prometheus sample per DNS rcode bucket.
func collectRcodeCounters(ch chan<- prometheus.Metric, desc *prometheus.Desc, m *ebpf.Map) {
	for rcode := uint32(0); rcode < 16; rcode++ {
		total := sumU64PerCPU(m, rcode)
		ch <- prometheus.MustNewConstMetric(desc, prometheus.CounterValue, float64(total), fmt.Sprint(rcode))
	}
}

// collectLog2Histogram converts the BPF program's fixed log2 bucket array into
// a Prometheus histogram. Bucket boundaries are powers of two.
func collectLog2Histogram(ch chan<- prometheus.Metric, desc *prometheus.Desc, m *ebpf.Map) {
	counts := make([]uint64, ndHistBuckets)
	var total uint64
	var estimatedSum float64

	for i := uint32(0); i < ndHistBuckets; i++ {
		count := sumU64PerCPU(m, i)
		counts[i] = count
		total += count

		// The BPF program stores only log2 buckets, not exact samples. Use the
		// bucket upper bound as a conservative sum estimate for _sum.
		estimatedSum += float64(count) * float64(log2UpperBound(i))
	}

	cumulative := make(map[float64]uint64, ndHistBuckets-1)
	var running uint64
	for i := uint32(0); i < ndHistBuckets-1; i++ {
		running += counts[i]
		cumulative[float64(log2UpperBound(i))] = running
	}

	ch <- prometheus.MustNewConstHistogram(desc, total, estimatedSum, cumulative)
}

// log2UpperBound returns the inclusive upper bound represented by a log2 bucket
// index used in the BPF histogram arrays.
func log2UpperBound(bucket uint32) uint64 {
	if bucket >= 63 {
		return math.MaxUint64
	}
	return uint64(1) << bucket
}

// sumU64PerCPU reads a per-CPU uint64 array value and sums all CPU slots.
func sumU64PerCPU(m *ebpf.Map, key uint32) uint64 {
	values, err := lookupPerCPU[uint64](m, key)
	if err != nil {
		log.Printf("collect %s[%d]: %v", m.String(), key, err)
		return 0
	}

	var total uint64
	for _, v := range values {
		total += v
	}
	return total
}

// lookupPerCPU handles per-CPU map reads for generated BPF value types. The
// runtime.NumCPU-sized slice works on most systems; the fallback lets cilium/ebpf
// size the slice dynamically if the kernel reports a different CPU count.
func lookupPerCPU[T any](m *ebpf.Map, key uint32) ([]T, error) {
	values := make([]T, runtime.NumCPU())
	if err := m.Lookup(&key, &values); err == nil {
		return values, nil
	}

	var dynamic []T
	if err := m.Lookup(&key, &dynamic); err != nil {
		return nil, err
	}
	return dynamic, nil
}

// ipv4String formats a uint32 IPv4 address from BPF event/map data for logs.
func ipv4String(ip uint32) string {
	var b [4]byte
	binary.LittleEndian.PutUint32(b[:], ip)
	return net.IP(b[:]).String()
}
