package bpf

// bpf2go compiles the kernel-side eBPF C program and generates Go wrappers
// such as bpfObjects, loadBpfObjects, and bpfNdEvent used by this package.
//
// Map key/value types are generated by default. Avoid explicit -type flags for
// nd_* names because several maps intentionally share names with their value
// structs, for example the nd_config map and struct nd_config.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -no-strip -target amd64 bpf ../../bpf/networkdoctor.bpf.c -- -I../../bpf -I../..
